healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('healthcentre.urls')),
    path('admin/', admin.site.urls),
    path('medicalstore/', include(('medicalstore.urls', 'medicalstore'), namespace = "medicalstore")),
    path('pedict/', include(('pedict.urls', 'pedict'), namespace = "pedict"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalstore/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('search', views.search, name = "search")
]

pedict/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('heart', views.heart, name="heart"),
    path('diabetes', views.diabetes, name="diabetes"),
    path('breast', views.breast, name="breast"),
    path('calories', views.calories, name="calories"),
    path('', views.home, name="home"),
]

medicalstore/models.py
from django.db import models

# Create your models here.

class Medicine(models.Model):
    name = models.CharField(unique = True, max_length = 150)
    company = models.CharField(max_length = 150)
    manufacturedDate = models.DateField()
    expiryDate = models.DateField()
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    photoId = models.CharField(unique = True, max_length = 100)

    def __str__(self):
        return "Name : " + str(self.name) + " Company : " + str(self.company) + " Manufactured Date : " + str(self.manufacturedDate) + " Expiry Date : " + str(self.expiryDate) + " Quantity : " + str(self.quantity)

medicalstore/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Medicine
# Create your views here.


def index(request):
    """ Function for displaying main page of Medical Store. """

    # Getting all the medicines from the database
    medicines = Medicine.objects.all()

    # Storing all the medicines available inside context variable
    context = {
        "medicines" : medicines.order_by('name')
    }

    # Editing response headers so as to ignore cached versions of pages
    response = render(request, "medicalstore/medicines.html", context)
    return responseHeadersModifier(response)

def search(request):
    """Function for displaying the search filtered medicines available in the database."""

    # If the user submits a search query
    if request.method == "POST":

        # Extracting the search query from post request
        searchQuery = request.POST["searchQuery"]

        # Getting the search results, i.e.,all the medicines containing
        # the search query as a substring
        searchFilteredMedicines = Medicine.objects.filter(name__contains = searchQuery)

        # Storing the search results inside the context variable
        context = {
            "medicines" : searchFilteredMedicines.order_by('name')
        }

        # Editing response headers so as to ignore cached versions of pages
        response = render(request, "medicalstore/medicines.html", context)
        return responseHeadersModifier(response)

    # Redirecting if the request method is get as searching requires some input
    elif request.method == "GET":

        # Editing response headers so as to ignore cached versions of pages
        response = HttpResponseRedirect(reverse('medicalstore:index'))
        return responseHeadersModifier(response)

    # Redirecting if the request method neither post nor get as searching requires some input
    else:

        # Editing response headers so as to ignore cached versions of pages
        response = HttpResponseRedirect(reverse('medicalstore:index'))
        return responseHeadersModifier(response)

def responseHeadersModifier(response):
    """Funtion to edit response headers so that no cached versions can be viewed. Returns the modified response."""
    response["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response["Pragma"] = "no-cache"
    response["Expires"] = "0"
    return response

medicalstore/templates/MedicalStore/layout.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <title>{% block title %}{% endblock %}</title>
        <style>{% block style %}{% endblock %}</style>
        <script src="{% static 'healthcentre/javascript/windowHistory.js' %}"></script>

    </head>

{% block bodytag %}
{% endblock %}

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
        {% if request.session.isLoggedIn %}
            <a class="navbar-brand" href="/"><h3 style="color:black;text-align:center">Hi,{% if request.session.isDoctor %} Dr.{% endif %} {{ request.session.Name }}</h3></a>
        {% else %}
            <a class="navbar-brand" href="/"><h2 style="color:black;text-align:center">HealthVista</h2></a>
        {% endif %}

        <img src="{% static 'healthcentre/images/jdh10.png' %}" style="width:5%;height:5%;"></img>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}" style="color:black;">Home <span class="sr-only">(current)</span></a>
                </li>

                {% if request.session.isLoggedIn %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black;">Your Prescriptions <span class="badge badge-primary badge-pill">{{ request.session.numberNewPrescriptions }} NEW</span></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black;">Login</a>
                      </li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" style="color:black;" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Options
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{% url 'medicalstore:index' %}">Medicine Store</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'doctors' %}">Doctors</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'contactus' %}">Contact Us</a>

                        {% if request.session.isLoggedIn %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}" style="color:black;">Logout</a>
                        {% endif %}

                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'onlineprescription' %}" style="color:black;">Online Prescription</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'emergency' %}"><span style="background-color:red" class="badge badge-secondary">EMERGENCY</span></a>
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'medicalstore:search' %}">
              {% csrf_token %}
                <input name = "searchQuery" class="form-control mr-sm-2" type="search" placeholder="Search Medicine" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </nav>
    <li class="dropdown-divider" style="margin-top:0px;margin-bottom:0px;border-color:black"></li>

{% block body %}

{% endblock %}

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        </body>
    </html>

medicalstore/templates/MedicalStore/medicines.html
{% extends "medicalstore/layout.html" %}

{% block title %}
HealthVista
{% endblock%}

{% block bodytag %}

  {% load static %}
  <body background="{% static 'healthcentre/images/22.jpg' %}" style="background-size: auto auto;">

{% endblock %}

{% block body %}

    <br>

    <h1 style="text-align:center;color:black;" class = "display-4">
      Medical Store
    </h1>

    <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;color:yellow;border-color:black"></li>

    <br>
    <br>

    {% for medicine in medicines %}
        <div class="row container"style="margin: 0 auto;" >
            <div class="col-sm-8" >
                <div class="card" style = "background:rgba(0,0,0,1.0);color:white;padding-bottom:17%">
                    <div class="card-body">

                        <h3 class="card-title"> {{ medicine.name }}</h3>
                        <li class="dropdown-divider"></li>
                        <p class="card-text"><pre style="color:white">Company             : {{ medicine.company }}<br>Manufacturing Date  : {{ medicine.manufacturedDate }}<br>Expiry Date         : {{ medicine.expiryDate }}<br>Quantity Remaining  : {{ medicine.quantity }}</pre></p>
                        <h2 class="card-link lead" style="color:yellow;margin-bottom:0;">Price : &#8377;{{ medicine.price }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-4" style = "background:rgba(0,0,0,1.0)">
              <div class="container"style="padding:5%" >
                            {% with 'medicalstore/images/'|add:medicine.photoId as image_static %}
                                  <img style="display: block;"src="{% static image_static %}" class="rounded mx-auto d-block img-fluid" alt="Responsive image">
                            {% endwith %}
              </div>

            </div>

        </div>
        <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;margin-top:1.5%;margin-bottom:0px"></li>
        <br>



    {% empty %}


        <h4 style="text-align:center;color:black" >
            Sorry! No medicines matching your query are available right now. Please try again later!
        </h4>

    {% endfor %}


{% endblock %}