healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('healthcentre.urls')),
    path('admin/', admin.site.urls),
    path('medicalstore/', include(('medicalstore.urls', 'medicalstore'), namespace = "medicalstore")),
    path('pedict/', include(('pedict.urls', 'pedict'), namespace = "pedict"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedict/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('heart', views.heart, name="heart"),
    path('diabetes', views.diabetes, name="diabetes"),
    path('breast', views.breast, name="breast"),
    path('calories', views.calories, name="calories"),
    path('', views.home, name="home"),
]

pedict/models.py
from django.db import models

# Create your models here.

pedict/forms.py
from django import forms


class BreastCancerForm(forms.Form):

    radius = forms.FloatField(label='Mean Radius', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    texture = forms.FloatField(label='Mean Texture', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    perimeter = forms.FloatField(label='Mean Perimeter', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    area = forms.FloatField(label='Mean Area', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    smoothness = forms.FloatField(label='Mean Smoothness', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class DiabetesForm(forms.Form):

    pregnancies = forms.FloatField(label='Pregnancies', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    glucose = forms.FloatField(label='Glucose', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    bloodpressure = forms.FloatField(label='Blood Pressure', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    skinthickness = forms.FloatField(label='Skin Thickness', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    insulin = forms.FloatField(label='Insulin', min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    bmi = forms.FloatField(label='BMI', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    pedigree = forms.FloatField(label='Pedigree', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    age = forms.FloatField(label='Age', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class HeartDiseaseForm(forms.Form):

    age = forms.FloatField(label='Age', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    sex = forms.FloatField(label='Sex', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    cp = forms.FloatField(label='CP', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    trestbps = forms.FloatField(label='TRESTBPS', min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    chol = forms.FloatField(label='CHOL', min_value=0, max_value=500, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    fbs = forms.FloatField(label='FBS', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    restecg = forms.FloatField(label='RESTECG', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    thalach = forms.FloatField(label='THALACH', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    exang = forms.FloatField(label='EXANG', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    oldpeak = forms.FloatField(label='OLDPEAK', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    slope = forms.FloatField(label='SLOPE', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    ca = forms.FloatField(label='CA', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    thal = forms.FloatField(label='THAL', min_value=0, max_value=300, widget=forms.NumberInput(attrs={'class': 'form-control'}))

pedict/views.py
from django.shortcuts import render
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import json

from pedict.forms import BreastCancerForm, DiabetesForm, HeartDiseaseForm

def calories(request):
    import requests

    if request.method == 'POST':

        query = request.POST['query']
        api_url = 'https://api.api-ninjas.com/v1/nutrition?query='
        api_request = requests.get (api_url + query, headers={'X-Api-Key': 'pqTXAVVQoVmNNBOgVhuGSA==Zntg6QuzVtX2uRDC'})

        try:
            api = json.loads(api_request.content)
            print(api_request.content)

        except Exception as e:
            api = "OOPS!! There was an error"
            print(e)
        return render(request, 'calori.html',{'api':api})
    
    else:
        return render(request, 'calori.html',{'query':'Enter a valid query'})

def heart(request):
    """ 
    18:39:18 09 Oct, 2019 by Arjun Adhikari
    Reading the training data set. 
    """
    df = pd.read_csv('static/Heart_train.csv')
    data = df.values
    X = data[:, :-1]
    Y = data[:, -1:]

    """ 
    18:39:18 09 Oct, 2019 by Arjun Adhikari
    Reading data from the user. 
    """

    value = ''

    if request.method == 'POST':

        age = float(request.POST['age'])
        sex = float(request.POST['sex'])
        cp = float(request.POST['cp'])
        trestbps = float(request.POST['trestbps'])
        chol = float(request.POST['chol'])
        fbs = float(request.POST['fbs'])
        restecg = float(request.POST['restecg'])
        thalach = float(request.POST['thalach'])
        exang = float(request.POST['exang'])
        oldpeak = float(request.POST['oldpeak'])
        slope = float(request.POST['slope'])
        ca = float(request.POST['ca'])
        thal = float(request.POST['thal'])

        user_data = np.array(
            (age,
             sex,
             cp,
             trestbps,
             chol,
             fbs,
             restecg,
             thalach,
             exang,
             oldpeak,
             slope,
             ca,
             thal)
        ).reshape(1, 13)

        rf = RandomForestClassifier(
            n_estimators=16,
            criterion='entropy',
            max_depth=9
        )

        rf.fit(np.nan_to_num(X), Y)
        rf.score(np.nan_to_num(X), Y)
        predictions = rf.predict(user_data)

        if int(predictions[0]) == 1:
            value = 'have'
        elif int(predictions[0]) == 0:
            value = "don\'t have"

    return render(request,
                  'heart.html',
                  {
                      'context': value,
                      'title': 'Heart Disease Prediction',
                      'active': 'btn btn-success peach-gradient text-white',
                      'heart': True,
                      'form': HeartDiseaseForm(),
                  })


def diabetes(request):
    """ 
    20:13:20 09 Oct, 2019 by Arjun Adhikari
    Reading the training data set. 
    """
    dfx = pd.read_csv('static/Diabetes_XTrain.csv')
    dfy = pd.read_csv('static/Diabetes_YTrain.csv')
    X = dfx.values
    Y = dfy.values
    Y = Y.reshape((-1,))

    """ 
    20:18:20 09 Oct, 2019 by Arjun Adhikari
    Reading data from user. 
    """
    value = ''
    if request.method == 'POST':

        pregnancies = float(request.POST['pregnancies'])
        glucose = float(request.POST['glucose'])
        bloodpressure = float(request.POST['bloodpressure'])
        skinthickness = float(request.POST['skinthickness'])
        bmi = float(request.POST['bmi'])
        insulin = float(request.POST['insulin'])
        pedigree = float(request.POST['pedigree'])
        age = float(request.POST['age'])

        user_data = np.array(
            (pregnancies,
             glucose,
             bloodpressure,
             skinthickness,
             bmi,
             insulin,
             pedigree,
             age)
        ).reshape(1, 8)

        knn = KNeighborsClassifier(n_neighbors=3)
        knn.fit(X, Y)

        predictions = knn.predict(user_data)

        if int(predictions[0]) == 1:
            value = 'have'
        elif int(predictions[0]) == 0:
            value = "don\'t have"

    return render(request,
                  'diabetes.html',
                  {
                      'result': value,
                      'title': 'Diabetes Disease Prediction',
                      'active': 'btn btn-success peach-gradient text-white',
                      'diabetes': True,
                      'form': DiabetesForm(),
                  }
                  )


def breast(request):
    """ 
    20:56:20 09 Oct, 2019 by Arjun Adhikari
    Reading training data set. 
    """
    df = pd.read_csv('static/Breast_train.csv')
    data = df.values
    X = data[:, :-1]
    Y = data[:, -1]
    print(X.shape, Y.shape)

    """ 
    20:57:20 09 Oct, 2019 by Arjun Adhikari
    Reading data from user. 
    """
    value = ''
    if request.method == 'POST':

        radius = float(request.POST['radius'])
        texture = float(request.POST['texture'])
        perimeter = float(request.POST['perimeter'])
        area = float(request.POST['area'])
        smoothness = float(request.POST['smoothness'])

        """ 
        21:02:21 09 Oct, 2019 by Arjun Adhikari
        Creating our training model. 
        """
        rf = RandomForestClassifier(
            n_estimators=16, criterion='entropy', max_depth=5)
        rf.fit(np.nan_to_num(X), Y)

        user_data = np.array(
            (radius,
             texture,
             perimeter,
             area,
             smoothness)
        ).reshape(1, 5)

        predictions = rf.predict(user_data)
        print(predictions)

        if int(predictions[0]) == 1:
            value = 'have'
        elif int(predictions[0]) == 0:
            value = "don\'t have"

    return render(request,
                  'breast.html',
                  {
                      'result': value,
                      'title': 'Breast Cancer Prediction',
                      'active': 'btn btn-success peach-gradient text-white',
                      'breast': True,
                      'form': BreastCancerForm(),
                  })


def home(request):

    return render(request,
                  'home.html')


""" 
20:07:20 10 Oct, 2019 by Arjun Adhikari
Handling 404 error pages. 
"""


def handler404(request):
    return render(request, '404.html', status=404)

pedict/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{{title}}</title>
  </head>
  <body class="{{background}}">
    {% include 'navbar.html' %}
    {% block content %} {% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

pedict/templates/breast.html
{%extends 'base.html'%} 

{%block content%}

<div class="container">
  <div class="display-4 my-2 text-center">Breast Cancer Prediction</div>
  <hr />
  {% if result %}
  <div class="h1 my-2 text-center">
    You {{ result }} breast cancer.
  </div>
  {% endif %}

  <!-- 
      19:46:19 09 Oct, 2019 by Arjun Adhikari
      Form Here 
      -->
  <div class="col-md-4">
    <form class="" method="POST" action="{% url 'pedict:breast' %}">
      {% csrf_token %}
      {{form}}
      <div class="mt-4">
        <button type="submit" class="btn-lg btn-block btn btn-outline-danger mb-5">
          Submit
        </button>
      </div>
    </form>
  </div>
  <br><br><br><br>
</div>
{%endblock%}

pedict/templates/diabetes.html
{%extends 'base.html'%}

{%block content%}
{% load static %}
<div class="container">
    <div class="display-4 my-2 text-center">Diabetes Disease Prediction</div>
    <hr />
    {% if result %}
    <div class="h1 my-2 text-center">
        You {{ result }} diabetes disease.
    </div>
    {% endif %}

    <!-- 
      19:46:19 09 Oct, 2019 by Arjun Adhikari
      Form Here 
      -->
    <div class="col-md-4">
        <form class="" method="POST" action="{% url 'pedict:diabetes' %}">
            {% csrf_token %}
            {{form}}
            <div class="mt-4">
                <button type="submit" class="btn-lg btn-block btn btn-outline-danger mb-5">
                    Submit
                </button>
                <img src="{% static 'images/dia.png' %}">
            </div>
        </form>
    </div>
    <br><br><br><br>
</div>

{% endblock %}

pedict/templates/heart.html
{%extends 'base.html'%} 

{%block content%}
{% load static %}
<div class="container">
    <div class="display-4 my-2 text-center">Heart Disease Prediction</div>
    <hr />
    {% if context %}
    <div class="h1 my-2 text-center">
        You {{ context }} heart disease.
    </div>
    {% endif %}

    <!-- 
      19:46:19 09 Oct, 2019 by Arjun Adhikari
      Form Here 
      -->
    <div class="col-md-4">
        <form class="" method="POST" action="{% url 'pedict:heart' %}">
            {% csrf_token %}
            {{form}}
            <div class="mt-4">
                <button type="submit" class="btn-lg btn-block btn btn-outline-danger mb-5">
                    Submit
                </button>
            <img src="{% static 'images/heart.png' %}">
            </div>
        </form>
    </div>
    <br><br><br><br>
</div>

{% endblock %}

pedict/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>Disease Predictor</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'pedict:home' %}">Disease Predictor</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link mr-3 " href="{% url 'index' %}"
            >Main Menu
          </a>
          <a class="nav-item nav-link mr-3 " href="{% url 'pedict:heart' %}"
            >Heart Disease Prediction
          </a>
          <a class="nav-item nav-link mr-3" href="{% url 'pedict:diabetes' %}"
            >Diabetes Disease Prediction
          </a>
          <a class="nav-item nav-link " href="{% url 'pedict:breast' %}"
            >Breast Cancer Prediction</a
          >
        </div>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-5">Hello, People!</h1>
      <p class="lead ">
        Machine learning models demonstrate high accuracy in diagnosing heart diseases, diabetes, and breast cancer. They analyze intricate patterns in medical data, aiding early detection and personalized treatment plans, thereby enhancing patient outcomes through reliable predictions and precise interventions.
      </p>
      <p>
        Powered by <strong>HealthVista</strong>
      </p>
      <p class="lead">
        <a class="btn btn-dark btn-lg" href="{% url 'index1' %}" role="button">Health Center</a>
      </p>
    </div>

    <section class="pricing py-5">
      <div class="container">
        <div class="row">
          <!-- Free Tier -->
          <div class="col-lg-4">
            <div class="card mb-5 mb-lg-0">
              <div class="card-body">
                <h5 class="card-title text-muted text-uppercase text-center">
                  HEART DISEASE PREDICTION
                </h5>

                <hr />
                <p class="">
                  Heart disease is one of the biggest cause for morbidity and
                  mortality among the population of the world. Prediction of
                  cardiovascular disease is regarded as one of the most
                  important subject in the section of clinical data analysis.
                  The amount of data in the healthcare industry is huge. Data
                  mining turns the large collection of raw healthcare data into
                  information that can help to make informed decision and
                  prediction.
                </p>
                <a
                  href="{% url 'pedict:heart' %}"
                  class="btn btn-block btn-danger text-uppercase"
                  >KNOW HEART STATUS</a
                >
              </div>
            </div>
          </div>
          <!-- Plus Tier -->
          <div class="col-lg-4">
            <div class="card mb-5 mb-lg-0">
              <div class="card-body">
                <h5 class="card-title text-muted text-uppercase text-center">
                  DIABETES PREDICTION
                </h5>

                <hr />
                <p class="">
                  Diabetes is considered as one of the deadliest and chronic
                  diseases which causes an increase in blood sugar. Many
                  complications occur if diabetes remains untreated and
                  unidentified. The tedious identifying process results in
                  visiting of a patient to a diagnostic center and consulting
                  doctor. But the rise in machine learning approaches solves
                  this critical problem.
                </p>
                <a
                  href="{% url 'pedict:diabetes' %}"
                  class="btn btn-block btn-dark text-uppercase"
                  >KNOW DIABETES STATUS</a
                >
              </div>
            </div>
          </div>
          <!-- Pro Tier -->
          <div class="col-lg-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title text-muted text-uppercase text-center">
                  BREAST CANCER PREDICTION
                </h5>

                <hr />
                <p class="">
                  Breast cancer is one of the most common cancers among
                  women worldwide, representing the majority of new cancer cases
                  and cancer-related deaths according to global statistics,
                  making it a significant public health problem in today’s
                  society.
                </p>
                <a
                  href="{% url 'pedict:breast' %}"
                  class="btn btn-block btn-primary text-uppercase"
                  >KNOW BREAST CANCER STATUS</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

pedict/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pedict:home' %}">Disease Predictor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link mr-3 {% if heart %} {{active}} {% endif %} " href="{% url 'pedict:heart' %}">Heart
                Disease Prediction
            </a>
            <a class="nav-item nav-link mr-3 {% if diabetes %} {{active}} {% endif %} "
                href="{% url 'pedict:diabetes' %}">Diabetes Prediction
            </a>
            <a class="nav-item nav-link mr-3 {% if breast %} {{active}} {% endif %} " href="{% url 'pedict:breast' %}">Breast
                Cancer Prediction</a>
        </div>
    </div>
</nav>