healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('healthcentre.urls')),
    path('admin/', admin.site.urls),
    path('medicalstore/', include(('medicalstore.urls', 'medicalstore'), namespace = "medicalstore")),
    path('pedict/', include(('pedict.urls', 'pedict'), namespace = "pedict"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthcentre/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

urlpatterns = [
    path('', views.index, name = "index"),
    path('index1', views.index1, name = "index1"),
    path('ov', views.ov, name = "ov"),
    path('water', views.water, name = "water"),
    path('main', views.main, name = "main"),
    path('sp', views.sp, name = "sp"),
    path('rem', views.rem, name = "rem"),
    path('arti', views.arti, name = "arti"),
    path('trys', views.trys, name = "trys"),
    path('comm', views.comm, name = "comm"),
    path('try1', views.try1, name = "try1"),
    path('vegan', views.vegan, name = "vegan"),
    path('gluten', views.gluten, name = "gluten"),
    path('article', views.article, name = "article"),
    path('article_1', views.article_1, name = "article_1"),
    path('article_2', views.article_2, name = "article_2"),
    path('article_homepage', views.article_homepage, name = "article_homepage"),
    path('np1', views.np1, name = "np1"),
    path('bmi', views.bmi, name = "bmi"),
    path('mg', views.mg, name = "mg"),
    path('register', views.register, name = "register"),
    path('doctors', views.doctors, name = "doctors"),
    path('login', views.login, name = "login"),
    path('emergency', views.emergency, name = "emergency"),
    path('logout', views.logout, name = "logout"),
    path('contactus', views.contactus, name = "contactus"),
    path('onlineprescription', views.onlineprescription, name = "onlineprescription")
]

pedict/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('heart', views.heart, name="heart"),
    path('diabetes', views.diabetes, name="diabetes"),
    path('breast', views.breast, name="breast"),
    path('calories', views.calories, name="calories"),
    path('', views.home, name="home"),
]

healthcentre/models.py
from django.db import models
from Crypto.Hash import SHA256
from codecs import encode,decode

class Doctor(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(unique = True, max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    specialization = models.CharField(max_length = 100)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email + " Specialization : " + self.specialization

class Patient(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    rollNumber = models.CharField(unique = True, max_length = 8)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email

class Prescription(models.Model):
    prescriptionText = models.CharField(max_length = 2000, default = "")
    doctor = models.ForeignKey(Doctor, related_name = "doctorRecords", on_delete = models.CASCADE)
    patient = models.ForeignKey(Patient, related_name = "patientRecords", on_delete = models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add = True)
    isNew = models.BooleanField(default = True)
    isCompleted = models.BooleanField(default = False)
    symptoms = models.CharField(max_length = 2000)

    def __str__(self):
        return "\nDoctor :" + str(self.doctor) + "\n\nPatient :" + str(self.patient) + "\n\nPrescription : \n\n" + self.prescriptionText + "\n\n"


def passwordHasher(userPassword):
    """Function to return the hash of the password using SHA-256. Input is the password of the user in string."""
    userPassword = userPassword
    SHA256Engine = SHA256.new()
    userPassword = userPassword.encode()
    SHA256Engine.update(userPassword)
    passwordHash = SHA256Engine.digest()
    passwordHash = encode(passwordHash, 'hex')
    passwordHash = decode(passwordHash, 'utf-8')
    return passwordHash


def emailHasher(userEmail):
    """Function to return the hash of the email using SHA-256. Input is the email of the user in string."""
    userEmail = userEmail
    SHA256Engine = SHA256.new()
    userEmail = userEmail.encode()
    SHA256Engine.update(userEmail)
    emailHash = SHA256Engine.digest()
    emailHash = encode(emailHash, 'hex')
    emailHash = decode(emailHash, 'utf-8')
    return emailHash

healthcentre/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Doctor, Patient, Prescription, passwordHasher, emailHasher
from django.db.models import Count, Q

# Create your views here.

def index(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/index.html")
    return responseHeadersModifier(response)

def index1(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/index1.html")
    return responseHeadersModifier(response)

def article(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/article.html")
    return responseHeadersModifier(response)

def article_1(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/article_1.html")
    return responseHeadersModifier(response)

def article_2(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/article_2.html")
    return responseHeadersModifier(response)

def article_homepage(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/article_homepage.html")
    return responseHeadersModifier(response)

def bmi(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/bmi.html")
    return responseHeadersModifier(response)

def trys(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/trys.html")
    return responseHeadersModifier(response)

def try1(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/try1.html")
    return responseHeadersModifier(response)

def ov(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/ov.html")
    return responseHeadersModifier(response)

def arti(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/arti.html")
    return responseHeadersModifier(response)

def sp(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/sp.html")
    return responseHeadersModifier(response)

def comm(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/comm.html")
    return responseHeadersModifier(response)

def rem(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/rem.html")
    return responseHeadersModifier(response)

def water(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/water.html")
    return responseHeadersModifier(response)


def vegan(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/vegan.html")
    return responseHeadersModifier(response)

def gluten(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/gluten.html")
    return responseHeadersModifier(response)


def np1(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/next-period-calculator.html")
    return responseHeadersModifier(response)

def mg(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/memory-game.html")
    return responseHeadersModifier(response)

def main(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/main.html")
    return responseHeadersModifier(response)


def register(request):
    """ Function for registering a student into the portal. """

    # If the user wants the page to get displayed
    if request.method == "GET":

        # Editing response headers so as to ignore cached versions of pages
        response =  render(request,"healthcentre/registrationPortal.html")
        return responseHeadersModifier(response)

    # If the user wants to submit his/her information
    elif request.method == "POST":

        # Extracting the user information from the post request
        userFirstName = request.POST["userFirstName"]
        userLastName = request.POST["userLastName"]
        userEmail = request.POST["userEmail"]
        userRollNo = request.POST["userRollNo"]
        userAddress = request.POST["userAddress"]
        userContactNo = request.POST["userContactNo"]
        userPassword = request.POST["userPassword"]
        userConfirmPassword = request.POST["userConfirmPassword"]

        # If both the passwords match
        if userPassword == userConfirmPassword:

            name = userFirstName + " " + userLastName

            # Encrypting password to store inside database
            passwordHash = passwordHasher(userPassword)

            # Encrypting email to store inside database
            emailHash = emailHasher(userEmail)

            # Creating a patient object and saving insdie the database
            patient = Patient(name = name,rollNumber = userRollNo, email = userEmail, passwordHash = passwordHash, address = userAddress, contactNumber = userContactNo, emailHash = emailHash )
            patient.save()

            # Storing success message in the context variable
            context = {
                "message":"User Registration Successful. Please Login."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request, "healthcentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

        # If the passwords given don't match
        else:
            # Storing failure message in the context variable
            context = {
                "message":"Passwords do not match.Please register again."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request,"healthcentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

    # For any other method of request, sending back the registration page.
    else:

        # Editing response headers so as to ignore cached versions of pages
        response = render(request,"healthcentre/registrationPortal.html")
        return responseHeadersModifier(response)


def doctors(request):
    """Function to send information about the doctors available to the user. """

    # Storing doctors available in the context variable
    context = {
        "doctors" : Doctor.objects.all()
    }

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"healthcentre/doctors.html",context)
    return responseHeadersModifier(response)


def login(request):
    """ Function for logging in the user. """

    # Calling session variables checker
    request = requestSessionInitializedChecker(request)

    # If the request method is post
    if request.method == "GET":
        try:

            # If the user is already logged in inside of his sessions, and is a doctor, then no authentication required
            if request.session['isLoggedIn'] and request.session['isDoctor']:

                # Accessing the doctor user and all his/her records
                doctor = Doctor.objects.get(emailHash = request.session['userEmail'])
                records = doctor.doctorRecords.all()

                # Getting the count of the new prescriptions pending
                numberNewPendingPrescriptions = doctor.doctorRecords.aggregate(newPendingPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = False) ) ))['newPendingPrescriptions']

                # Storing the same inside the session variables
                request.session['numberNewPrescriptions'] = numberNewPendingPrescriptions

                # Storing the required information inside the context variable
                context = {
                    "message" : "Successfully Logged In.",
                    "isAuthenticated" : True,
                    "user": records.order_by('-timestamp')
                }

healthcentre/templates/HealthCentre/article.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Professional Article</title>
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        header {
            background: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
        }
        .container {
            max-width: 800px;
            margin: auto;
            padding: 20px;
        }
        .article {
            margin-bottom: 20px;
        }
        .article h2 {
            color: #333;
        }
        .article p {
            color: #666;
        }
        .article img {
            max-width: 100%;
            margin-bottom: 10px;
        }
        footer {
            background: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
        }
    </style>
</head>
<body background="{% static 'healthcentre/images/22.jpg' %}" style="background-size: auto auto;">
    <header>
        <h1>Articles</h1>
    </header>
    <div class="container">
        <div class="article">
            <h2>Boosting Immunity: Natural Remedies</h2>
           
            
            <img src="{% static 'healthcentre/images/article_1.jpg' %}" alt="Article Image">
            <p>Discover effective natural ways to boost your immune system and stay healthy.</p>
            <a href="{% url 'article_1' %}" class="btn">Read More</a>
        </div>
        <div class="article">
            <h2>Yoga and Meditation for Stress Relief</h2>
            <img src="{% static 'healthcentre/images/article_2.jpg' %}" alt="Article Image">
            <p>Learn how practicing yoga and meditation can help reduce stress and promote relaxation.</p>
            <a href="{% url 'article_2' %}" class="btn">Read More</a>
            
        </div>
    </div>
    <footer>
        <p>&copy; 2023 Professional Article. All rights reserved.</p>
    </footer>
</body>
</html>

healthcentre/templates/HealthCentre/article_1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthVista</title>
    <style>
         body {
            font-family: Arial, sans-serif;
            line-height: 2.0;
            margin: 0;
            padding: 0;
        }
        header {
            background: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
        }
        .container {
            max-width: 800px;
            margin: auto;
            padding: 20px;
        }
        .article {
            margin-bottom: 20px;
            text-align: justify;
        }
        .article h2 {
            color: #333;
        }
        .article p {
            color: #666;
        }
        .article img {
            max-width: 100%;
            margin-bottom: 10px;
            text-align: justify;
        }
        footer {
            background: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
        }
    </style>
</head>
<body background="{% static 'healthcentre/images/22.jpg' %}" style="background-size: auto auto;">
    <header>
        <h1>Article-1</h1>
    </header>
    <div class="container">
        <div class="article">
            <h2>Boosting Immunity: Natural Remedies</h2>
            <p>

            Maintaining a robust immune system is essential for overall health, especially in our ever-changing world. 
            While the market is flooded with supplements and products claiming to boost immunity, the key lies in a balanced lifestyle and wise choices rather than a pill or powder. 
            Your immune system's delicate equilibrium must be upheld, strong enough to combat illness yet avoiding overreactions. 
            To navigate this complexity, science-backed methods offer a road-map to a healthy immune system.
            <br><br>

            <bold>1. Balanced Nutrition:-</bold>
            A nutritious diet is pivotal for a strong immune system. Incorporate vegetables, fruits, legumes, whole grains, lean proteins, and healthy fats. 
            Micro-nutrients like Vitamin B6, C, E, Zinc, and Magnesium maintain immune system homeostasis. 
            Consuming these nutrients from dietary sources is recommended to best support immunity.
            <br><br>

            2. Regular Exercise:-
            Physical activity is vital not only for fitness but also for a robust immune system. 
            Moderate-intensity exercise mobilizes immune cells, enhancing immune surveillance and promoting efficiency in detecting and reacting to infections.
            <br><br>

            3. Adequate Hydration:-
            Water plays a crucial role in immune function. Blood and lymph, carriers of immune cells, require water to circulate effectively. 
            Replenishing lost water is essential for immune support.

            <br><br>
            4. Quality Sleep:-
            Sleep is a vital process for immune function and homeostasis. 
            Prioritize optimal sleep duration to bolster your body's defense mechanisms.
            <br><br>
            </p>
            
            <img src="{% static 'healthcentre/images/article_1.jpg' %}" alt="Article Image">



            <p> 5. Stress Management:-
            Chronic stress impacts health, potentially weakening the immune system. 
            Identify stressors and adopt strategies like deep breathing, meditation, and exercise to alleviate stress's effects.
            <br><br>

            6. Whole Plant Foods:-
            Fruits, vegetables, nuts, seeds, and legumes rich in nutrients and antioxidants combat inflammation, benefiting immunity. 
            A healthy gut micro-biome nourished by plant-based fiber aids immunity.
            <br><br>

            7. Healthy Fats:-
            Healthy fats, such as those found in olive oil and omega-3 rich sources, reduce inflammation, and support immune response.

            8. Limit Added Sugars:-
            Curbing added sugars is crucial as they contribute to obesity and inflammation, weakening the immune system. 
            Reducing sugar intake aids weight loss and overall health.
            <br><br>
        </p>
        </div>
        <div class="article">
            <h2>Conclusion</h2>
            <p>
            Amid the sea of immunity-boosting claims, the science is clear-there's no shortcut to a strong immune system. 
            It thrives on a balanced lifestyle encompassing nutrition, exercise, hydration, sleep, and stress management. 
            Incorporating whole plant foods, healthy fats, and reducing added sugars provides a solid foundation for immune health. 
            By embracing these natural remedies, you empower your body to face the world's challenges head-on, ensuring a resilient and robust immune system for a healthier future.
            <br><br>    
            Disclaimer: This article is for informational purposes only and should not replace professional medical advice.
            </p>
        </div>
    </div>
    <footer>
        <p>&copy; 2023 Professional Article. All rights reserved.</p>
    </footer>
</body>
</html>

healthcentre/templates/HealthCentre/comm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/comm.css' %}">
    <title>Five Card Website</title>
</head>
<body background="{% static 'healthcentre/images/22.jpg' %}" style="background-size: auto auto;">
    <div class="card-container">
        <div class="card">
            <h1>Calori Tracker</h1>
            <h2> Monitor and manage your daily caloric intake and expenditure to support your health and fitness goals.</h2>
            <ul>
                <li>Your daily calories consumption should be between 1500 to 3000</li>
                <li>Monitors energy intake for informed, balanced dietary choices and goals.</li>
                <li>Calorie regulation ensures energy balance, weight control, and overall health through informed dietary choices.</li>
            </ul>
            <button><a style="color: white; text-decoration: none;" href="{% url 'pedict:calories' %}">Check</a></button>
        </div>

        <div class="card">
            <h1>BMI</h1>
            <h2>BMI calculator evaluates weight status, aiding health assessment and disease prevention strategies effectively.</h2>           
            <ul>
                <li>Your BMI range should be between 18.5 and 24.9</li>
                <li>Enhances portion awareness, fostering mindful eating habits.</li>
                <li>Supports weight management by quantifying energy intake and expenditure</li>
            </ul>
            <button><a style="color: white; text-decoration: none;" href="{% url 'bmi' %}">Check</a></button>
        </div>

        <div class="card">
            <h1>Period Tracker</h1>
            <h2>Breaks taboos, fosters open conversations, and promotes body positivity.</h2>
            <ul>
                <li>Tracks menstrual patterns, aiding early detection of irregularities or health concerns.</li>
                <li>Emotional well-being, guidance, and mood pattern recognition.</li>
                <li>Health records, condition management, personalized care, and informed discussions.</li>
            </ul>
            <button><a style="color: white; text-decoration: none;" href="{% url 'np1' %}">Check</a></button>
        </div>

        <div class="card">
            <h1>Sleep Tracker</h1>
            <h2>Quality sleep vital for physical health, cognitive function, emotional well-being, and overall daily performance.</h2>
            <ul>
                <li>Monitor sleep patterns, detect issues, and improve overall sleep quality.</li>
                <li>Unique sleep data aids identifying sleep disorders like sleep apnea, leading to timely medical intervention.</li>
                <li> Insights into sleep cycles optimize rest, enhancing memory, concentration, and overall cognitive function.</li>
            </ul>
            <button><a style="color: white; text-decoration: none;" href="{% url 'sp' %}">Check</a></button>
        </div>

        <div class="card">
            <h1>Water Tracker</h1>
            <h2>Hydration essential for bodily functions, energy, skin health, digestion, and overall well-being. Stay hydrated always.</h2>
            <ul>
                <li>Promotes hydration, supports bodily functions, and aids digestion and detoxification.</li>
                <li>Prevents dehydration, optimizes skin health, and boosts energy levels throughout the day.</li>
                <li>Tracks intake, encourages healthy habits, and ensures sufficient daily water consumption.</li>
            </ul>
            <button><a style="color: white; text-decoration: none;" href="{% url 'water' %}">Check</a></button>
        </div>
    </div>
    <br><br><br><br>
</body>
</html>

healthcentre/templates/HealthCentre/contactus.html
{% extends "healthcentre/layout.html" %}

{% block title %}
HealthVista
{% endblock %}

{% block bodytag %}

  {% load static %}
  <body background="{% static 'healthcentre/images/22.jpg' %}" style="background-size: auto auto;">

{% endblock %}

{% block body %}
    <br>

    <div class="jumbotron jumbotron-fluid" style = "margin-left:5%;margin-right:5%;background:rgba(0,0,0,0.6);color:white;">
        <div class="container">

            <h1 >Address</h1>

            <p class="lead">Kumarswami layout Teachers colony, DSCE Banglore, Banashankari, Banglore, Karnatak</p>
            <button class="btn btn-info" >Pin Code : 560063</button>

            <br>
            <br>

            <h1>Email</h1>

            <p class="lead">Suggestions and feedback are thoroughly welcomed.</p>
            <button class="btn btn-info" >HealthVista.9590@gmail.com</button>

            <br>
            <br>

            <h1 >Reception Contact Numbers</h1>

            <p class="lead">Please feel free to call us anytime. 24 x 7 Helpline Availability.</p>
            <button class="btn btn-info" >Contact Numbers : 0141-3562834, 0141-35682104</button>

        </div>
    </div>

{% endblock %}

healthcentre/templates/HealthCentre/index.html
<!DOCTYPE html>
{% load static %}
<!-- Coding By CodingNepal - www.codingnepalweb.com -->
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthVista</title>
    <!-- Linking Google font link for icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <link rel="stylesheet" href="{% static 'css/styles3.css' %}">
  </head>
  <body background="{% static 'healthcentre/images/11.jpg' %}">
     <center><div class="row container" style="font-size: 36px; margin-bottom: 16px; color: #fff; display: flex; min-height: 100vh; height: 100%; width: 90%; padding: 0 60px; gap: 30px; justify-content: space-between;">
          <div class="column" style="color: black;">
            <h2 style="margin-left: 5rem;">"HealthVista: Nurturing Wellness Through  <br />Proactive and Positive Living"</h2>
            <p style="margin-left: 10rem;">Proactive wellness cultivates strong bonds, prioritizes preventive health measures, encourages open communication, and fosters a supportive environment, enhancing overall physical, mental, and emotional well-being.</p>
          </div>
        </div></center>
    <aside class="sidebar">
      <div class="logo">
        <img src="{% static 'healthcentre/images/logo1.png' %}" alt="logo">
        <h2>HealthVista</h2>
      </div>
      <ul class="links">
        <h4>Main Menu</h4>
        <li>
          <span class="material-symbols-outlined">dashboard</span>
          <a href="{% url 'main' %}">Dashboard</a>
        </li>
        <li>
          <span class="material-symbols-outlined">show_chart</span>
          <a href="{% url 'index1' %}">Health Centre</a>
        </li>
        <li>
          <span class="material-symbols-outlined">flag</span>
          <a href="{% url 'pedict:home' %}">Report Analyzer</a>
        </li>
        <hr>
        <h4>Advanced</h4>
        <li>
          <span class="material-symbols-outlined">monitoring</span>
          <a href="http://localhost:8501/">RevAI</a>
        </li>
        
        <li>
          <span class="material-symbols-outlined">group</span>
          <a href="{% url 'article_homepage' %}">NewsLetter </a>
        </li>
        <li>
          <span class="material-symbols-outlined">pacemaker</span>
          <a href="{% url 'comm' %}">Body Regulation</a>
        </li>
        <li>
          <span class="material-symbols-outlined">ambient_screen</span>
          <a href="{% url 'mg' %}">Memory Game</a>
        </li>
        
        
        <hr>
        <h4>Account</h4>
        <li>
          <span class="material-symbols-outlined">person</span>
          <a href="{% url 'login' %}">Login/Register</a>
        </li>
        <li>
          <span class="material-symbols-outlined">bar_chart</span>
          <a href="{% url 'ov' %}">Overview</a>
        </li>
        <li>
          <span class="material-symbols-outlined">mail</span>
          <a href="{% url 'contactus' %}">Contact</a>
        </li>
        <li class="logout-link">
          <span class="material-symbols-outlined">logout</span>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </aside>
    <script src="{% static 'healthcentre/javascript/bot.js' %}" type="text/javascript"></script>
  </body>
</html>